import json

def cargar_profesores(ruta='data/profesores.json'):
    ...

def cargar_asignaturas(ruta='data/asignaturas.json', profesores=[]):
    ...

def guardar_profesores(profesores, ruta='data/profesores.json'):
    ...

def guardar_asignaturas(asignaturas, ruta='data/asignaturas.json'):
    ...
